
storage:
    dbPath: "/Users/trozdol/Server/_databases/mongo"
    journal:
        enabled: true
systemLog:
    destination: file
    path: "var/log/mongod.log"
    logAppend: true
    timeStampFormat: iso8601-utc
net:
    bindIp: 127.0.0.1
    port: 27017
    wireObjectCheck : false
    unixDomainSocket:
        enabled : true
setParameter:
   enableLocalhostAuthBypass: true

# processManagement:
#     fork: true
# security:
#     keyFile: "/data/key/rs1.key"
#     authorization: "enabled"
